# Generated by Django 2.0.7 on 2018-11-05 08:35

from django.db import migrations, models
import django.db.models.deletion
import functools
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service_at', models.DateField(default='2018-08-08')),
                ('next_service_at', models.DateField(default='2018-10-30')),
                ('last_odometer_reading', models.PositiveIntegerField(default=15000)),
                ('next_odometer_reading', models.PositiveIntegerField(default=30000)),
                ('last_service_provider', models.CharField(default='Volkwagon Glen Waverley', max_length=256)),
                ('service_report', models.FileField(upload_to=services.models.ServiceRecord.get_contract_upload_path)),
                ('file_upload_date', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='TyreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Repair', 'Repaired'), ('Replace', 'Replaced')], default='Repair', max_length=32)),
                ('tyre_position', models.CharField(choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('RL', 'Rear Left'), ('RR', 'Rear Right'), ('FT', 'Front Two'), ('RT', 'Rear Two'), ('A', 'All')], default='A', max_length=32)),
                ('number', models.PositiveIntegerField(default=4)),
                ('last_service_at', models.DateField(default='2018-09-10')),
                ('service_report', models.FileField(upload_to=services.models.TyreRecord.get_contract_upload_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_history', to='cars.Car')),
            ],
        ),
    ]
