# Generated by Django 2.0.7 on 2018-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_tyrerecord_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='last_service_at',
            field=models.DateField(default='2018-11-05'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='next_service_at',
            field=models.DateField(default='2019-02-20'),
        ),
        migrations.AlterField(
            model_name='tyrerecord',
            name='last_service_at',
            field=models.DateField(default='2018-11-05'),
        ),
    ]
