# Generated by Django 2.0.7 on 2018-11-05 08:35

import cars.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128)),
                ('year', models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2018', max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=256)),
                ('color', models.CharField(default='White', max_length=64)),
                ('rego', models.CharField(max_length=128, unique=True)),
                ('engine_no', models.CharField(max_length=256, unique=True)),
                ('vin', models.CharField(max_length=256, unique=True)),
                ('transmission', models.CharField(max_length=256)),
                ('options', models.CharField(blank=True, max_length=256)),
                ('maintenance_status', models.CharField(max_length=256)),
                ('lease_start_date', models.DateField(default='2018-02-14')),
                ('lease_term', models.PositiveIntegerField(default=36)),
                ('rental', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('distance_restrict', models.DecimalField(decimal_places=2, default=210000, max_digits=10)),
                ('start_odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('excess_kmcharge', models.DecimalField(decimal_places=2, default=0.12, max_digits=10)),
                ('default_interest', models.DecimalField(decimal_places=2, default=0.18, max_digits=10)),
                ('lessor', models.CharField(choices=[('S', 'Street Fleet'), ('P', 'PRS Owned')], default='S', max_length=8)),
                ('status', models.CharField(choices=[('A', 'Active'), ('S', 'In Service'), ('I', 'In Idle')], default='A', max_length=8)),
                ('rego_exp', models.DateField(default='2019-06-30')),
                ('insurer', models.CharField(default='AAMI', max_length=128)),
                ('policy_num', models.CharField(default='P12345678', max_length=128)),
                ('insurance_exp', models.DateField(default='2019-06-30')),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('contract', models.FileField(upload_to=cars.models.Car.get_contract_upload_path)),
                ('file_upload_date', models.DateField(default='2018-06-30')),
            ],
            options={
                'ordering': ['rego'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=32, unique=True)),
                ('license', models.CharField(default=1234567890, max_length=128)),
                ('email', models.CharField(default=None, max_length=256, null=True)),
                ('dept', models.CharField(choices=[('BG', 'Brown Goods'), ('WG', 'White Goods'), ('BL', 'Billing Team'), ('AC', 'Accountants'), ('CC', 'Call Center'), ('IT', 'IT Department'), ('MG', 'Management'), ('SP', 'Spare Parts'), ('HHP', 'Mobile Phones'), ('BDM', 'Business Development')], default='BG', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrivingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_records', to='cars.Car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_records', to='cars.Driver')),
            ],
            options={
                'ordering': ['car', '-start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('name', 'mobile', 'dept')},
        ),
    ]
