# Generated by Django 2.0.7 on 2018-11-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='file_upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(choices=[('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2016', max_length=32),
        ),
    ]
