# Generated by Django 2.0.8 on 2018-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181106_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingrecord',
            name='note',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
